### ISSUE TITLE
Simplify bidirectionalization scheme

### ISSUE THREAD

**Issue by ochafik** [google/dart-scissors#23]
We should consider a simplification of the bidirectionalization scheme (see issue #4), to output smaller css code. The following example:

  ```css
  a {
    foo: bar;
    margin-left: 1em;
  }
  ```

  Is currently transformed into:
  ```css
  a {
    foo: bar;
  }
  :host-context([dir="ltr"]) a {
    margin-left: 1em;
  }
  :host-context([dir="rtl"]) a {
    margin-right: 1em;
  }
  ```

  But could be shorter with:
  ```css
  a {
    foo: bar;
    margin-left: 1em;
  }
  :host-context([dir="rtl"]) a {
    margin-right: 1em;
  }
  ```
