### ISSUE TITLE
Perform RTL mirroring of CSS

### ISSUE THREAD

**Issue by ochafik** [google/dart-scissors#4]
There are two options:
* Fork out to [cssjanus](https://github.com/cssjanus/cssjanus) ([demo](https://cssjanus.github.io/)) when some transformer setting says so (requires a build per direction).
  * Note: can use [Google's original cssjanus.py](https://github.com/cegov/wiki/blob/master/maintenance/cssjanus/cssjanus.py)
* Perform ad-hoc transform using [css direction tricks](https://css-tricks.com/almanac/properties/d/direction/) (single build for both ltr & rtl)

  ```css
  a {
    foo: bar;
    margin-left: 1em;
  }
  ```

  To the following (edited with `:host-context`, [see spec](http://www.w3.org/TR/css-scoping-1/#host-selector) and see thread below):
  ```css
  a {
    foo: bar;
  }
  :host-context([dir="ltr"]) a {
    margin-left: 1em;
  }
  :host-context([dir="rtl"]) a {
    margin-right: 1em;
  }
  ```
(this would also use `cssjanus`, with extra logic to know which properties are flippable and to recombine the three portions: orientation-neutral, non-flipped orientation-specific, flipped orientation-specific)

**Comment by ochafik** [comment]
Update: seems that `[dir="rtl"]` only selects elements which have the `dir` attribute set (it's not inherited), and `:dir(rtl)` doesn't work in any browser yet (part of [CSS4 draft spec](http://www.w3.org/TR/selectors4/); `-moz-dir(rtl)` only works on Mozilla).

Now, what does seem to work is:
```css
*[dir="rtl"] a {
  float: right;
  background-color: yellow;
}
*[dir="ltr"] a {
  float: left;
  background-color: green;
}
```
But it's hacked away by the Angular2 transformer, becoming something like:
```
*[dir="rtl"][_ngcontent-xcg-1] .icon[_ngcontent-xcg-1] {
float:  left;background-color:  yellow;
}

*[dir="ltr"][_ngcontent-xcg-1] .icon[_ngcontent-xcg-1] {
float:  right;background-color:  green;
}
```

If the Angular2 transformer could leave that `*[dir=...]` alone and not specialize it to the template content attribute, or if it were compiling the `:dir(rtl)` pseudo selector to just `*[dir="rtl"]`, it would save the day and make this approach to work.

**Comment by ochafik** [comment]
Got lots of intel / ideas from @tbosch: looks like Angular2 already supports some special selectors that allow working around shimming (i.e. the extra `[_ngcontent-xcg-1]` watermarks that specialize the selectors for a given component).

First, [`@polyfill-unscoped-rule`](https://github.com/Polymer/docs/issues/174) would allow us to escape from shimming altogether:

```css
@polyfill-unscoped-rule {
 content: '*[dir="ltr"] a';
}
::content {
  float: left;
  background-color: green;
}
```
Would be compiled to:
```css
*[dir="ltr"] a {
  float: left;
  background-color: green;
}
```
Which... isn't shimmed, so we'd loose style encapsulation... And `@polyfill-rule` seems to shims everything, so we'd need another special notation (e.g. `@ng-preserve-next *[dir="rtl"] a`), which we'll ask for to the Angular team (TODO(ochafik): link to a2 tracking issue when filed).

But in the meantime, we can shim it ourselves, as the static compilation actually uses a placeholder `%COMP%`, which is replaced at runtime by the actual globally-unique component attribute (`_ngcontent-xcg-1` in the example above).

So... modulo syntax issues, the following:
```css
@polyfill-unscoped-rule {
 content: '*[dir="ltr"] a[%COMP%]';
}
::content {
  float: left;
  background-color: green;
}
```
Should be compiled, then loaded / replaced at runtime as the following:
```css
*[dir="ltr"] a[_ngcontent-xcg-1] {
  float: left;
  background-color: green;
}
```
