### ISSUE TITLE
Bidi CSS broken

### ISSUE THREAD

**Issue by ochafik** [google/dart-scissors#43]
In versions up to 0.6.0+1 (issue #23), the following snippet:

```css
foo { margin-left: 1px }
```

Is bidirectionalized to:

```css
foo { margin-left: 1px }
:host-context([dir="rtl"]) foo { margin-right: 1px }
```

Which is incorrect (a margin-left does not counteract a margin-right). It should be the following instead:

```css
:host-context([dir="ltr"]) foo { margin-left: 1px }
:host-context([dir="rtl"]) foo { margin-right: 1px }
```

Already fixed by @MonamAgarwal in https://github.com/google/dart-scissors/commit/2873219811dfad23d2c42c9db18a03c782af5df4, now need a new release.
